# Generated by Django 6.0.5 on 2026-05-31 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('property_name', models.CharField(max_length=255)),
                ('strength_summary', models.TextField(blank=True)),
                ('weakness_summary', models.TextField(blank=True)),
                ('actionable_advice', models.TextField(blank=True)),
                ('overall_narrative', models.TextField(blank=True)),
                ('total_home', models.IntegerField(default=0)),
                ('avg_reviewer_score', models.FloatField(default=0.0)),
                ('sentiment_breakdown', models.JSONField(default=dict)),
                ('top_topics', models.JSONField(default=list)),
                ('aspect_scores', models.JSONField(default=dict)),
                ('swahili_feedback_count', models.IntegerField(default=0)),
                ('swahili_sentiment_avg', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property insight',
                'verbose_name_plural': 'Property insights',
                'ordering': ['-total_home'],
            },
        ),
        migrations.CreateModel(
            name='TopicCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('review_count', models.IntegerField(default=0)),
                ('avg_sentiment_score', models.FloatField(default=0.5)),
                ('top_properties', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topic cluster',
                'verbose_name_plural': 'Topic clusters',
                'ordering': ['-review_count'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_name', models.CharField(db_index=True, max_length=255)),
                ('property_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reviewer_score', models.FloatField(blank=True, null=True)),
                ('positive_text', models.TextField(blank=True)),
                ('negative_text', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('kaggle', 'Kaggle 515k'), ('afrisenti', 'AfriSenti'), ('live', 'Live submission')], db_index=True, max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('other', 'Other')], db_index=True, default='en', max_length=10)),
                ('review_date', models.DateField(blank=True, db_index=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], db_index=True, max_length=10, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_model', models.CharField(blank=True, max_length=50)),
                ('topic_labels', models.JSONField(blank=True, default=list)),
                ('key_phrases', models.JSONField(blank=True, default=list)),
                ('aspect_scores', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'home',
                'ordering': ['-review_date', '-created_at'],
                'indexes': [models.Index(fields=['property_id', 'sentiment', 'review_date'], name='home_review_propert_ddabc0_idx'), models.Index(fields=['source', 'language', 'is_processed'], name='home_review_source_784c01_idx'), models.Index(fields=['sentiment', 'review_date'], name='home_review_sentime_5f8b34_idx')],
            },
        ),
        migrations.CreateModel(
            name='SentimentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_id', models.CharField(db_index=True, max_length=100)),
                ('property_name', models.CharField(max_length=255)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_home', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('avg_sentiment', models.FloatField(default=0.5)),
                ('top_topics', models.JSONField(default=list)),
                ('aspect_averages', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Sentiment snapshot',
                'verbose_name_plural': 'Sentiment snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['property_id', 'snapshot_date'], name='home_sentim_propert_6acea8_idx'), models.Index(fields=['snapshot_date', 'avg_sentiment'], name='home_sentim_snapsho_6e8dae_idx')],
                'unique_together': {('property_id', 'snapshot_date')},
            },
        ),
    ]
